"""Fixed task table

Revision ID: 9695706a32b7
Revises: 0a4cef0b9243
Create Date: 2023-10-19 15:24:27.994497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9695706a32b7'
down_revision: Union[str, None] = '0a4cef0b9243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_user_id_key', 'task', ['user_id'])
    # ### end Alembic commands ###
