"""Delete phone_number

Revision ID: b48dd77d8f75
Revises: f8834b9e6b59
Create Date: 2023-10-18 15:22:23.426974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48dd77d8f75'
down_revision: Union[str, None] = 'f8834b9e6b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phone_number', table_name='user')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.create_index('ix_user_phone_number', 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###
